### ISSUE TITLE
can't check out or fork and check out this repo

### ISSUE THREAD

**Issue by bahmutov** [ryanfiller/portfolio-gatsby-v2#55]
I tried with `git-lfs` and without forking and checking out this repo, but it immediately breaks and deletes lots of files

```
$ cd portfolio-gatsby-v2/
~/git/portfolio-gatsby-v2 on master*
$ g st
## master...origin/master
D  .eslintrc.js
D  .gitattributes
D  .gitignore
D  .lfsconfig
D  LICENSE
D  README.md
D  cypress.json
D  cypress/fixtures/example.json
D  cypress/integration/components/change.spec.js
D  cypress/integration/components/content/meta.spec.js
D  cypress/integration/components/content/post-preview.spec.js
D  cypress/integration/components/layout/banner.spec.js
D  cypress/integration/components/layout/banners/blog-banner.spec.js
D  cypress/integration/components/layout/banners/default-banner.spec.js
D  cypress/integration/components/layout/footer.spec.js
D  cypress/integration/components/layout/header.spec.js
...
```

which is very weird. With `git-lfs` it blocks asking for netlify password ...

I wanted to see what the test does, and spy from the test

```js
const setCssColor = (colorName, colorValue) => {
    document.documentElement.style
    .setProperty(`--${colorName}`, colorValue)
  }

// from test
cy.document()
  .its('documentElement.style')
  .then(style => cy.spy(style, 'setProperty').as('changeColor'))
cy.get('.input') // then pick new color value
cy.get('@changeColor')
  .should('have.been.calledWith', '--root', 'red') // or something
```

**Comment by ryanfiller** [comment]
Huh, interesting. This is my first time using gitLFS, which even then I'm using wrapped in Netfliy Large Media. I have a feeling this is why it asks for a password, but I'm surprised you can't just clone the repo.

I'll look into seeing I can do something similar and using `cy.spy`.
I'm not sure how much this will help, but I did push this code live. If you want to run something with `cy.visit('https://www.ryanfiller.com/styles')` and mess around with a test you can now.

**Comment by bahmutov** [comment]
No worries. I did experiment with color input last night and will write a blog post about it
